# Generated by Django 4.1.2 on 2022-10-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=50)),
                ('years_of_exp', models.PositiveIntegerField()),
                ('review', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
