# Generated by Django 4.1.2 on 2022-10-13 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_level',
            field=models.CharField(default="now", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.URLField(default="www.abv.b-g"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='works_full_time',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
