# Generated by Django 4.1.2 on 2022-10-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_employee_birth_date_employee_created_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NullBlankDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blank', models.IntegerField(blank=True)),
                ('null', models.IntegerField(null=True)),
                ('blanknull', models.IntegerField(blank=True, null=True)),
                ('default', models.IntegerField()),
            ],
        ),
    ]
