# Generated by Django 4.1.2 on 2022-10-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_nullblankdemo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nullblankdemo',
            name='blank',
        ),
        migrations.RemoveField(
            model_name='nullblankdemo',
            name='null',
        ),
        migrations.AddField(
            model_name='employee',
            name='level',
            field=models.CharField(choices=[('Jr', 'Junior'), ('Mid', 'Middle'), ('Snr', 'Senior')], default='Jr', max_length=25),
            preserve_default=False,
        ),
    ]
