# Generated by Django 4.1.2 on 2022-10-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_employee_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('code_name', models.CharField(max_length=30, unique=True)),
                ('deadline', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='projects',
            field=models.ManyToManyField(to='web.project'),
        ),
    ]
